#!/bin/sh
;--------;
; COLORS ;
;--------;
[colors]
;background = ${xrdb:color0:#222}
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground-alt = #777
foreground-charging = #ffd61a
primary = #ffb52a
secondary = #e60053
alert = #bd2c40
background = #282828
foreground = #ebdbb2
border-color = 0

[bar/mainBar]

;------------;
; DIMENSIONS ;
;------------;

foreground = #ebdbb2
background = ${colors.background}
width = 100%
height = 26
offset-y = 0
offset-x = 0
radius = 2

border-top-size = 1
border-bottom-size = 1
border-right-size = 1
border-left-size = 0

;----------;
; LOCATION ;
;----------;

bottom = false
monitor = ${env:MONITOR:}
;monitor = DP1-2
;override-redirect = false

;-------;
; FONTS ;
;-------;

font-0 = Hack:size=10;3
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=12;3"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=12;3"
font-3 = "Font Awesome 5 Brands:pixelsize=12;3"
font-4 = Hack:size=10:weight=bold;2



;---------------;
; MISCELLANEOUS ;
;---------------;

fixed-center = true
padding-left = 0
padding-right = 2
module-margin = 1.5

modules-left = i3
modules-center = date time
modules-right = wlan cpu memory temperature volume backlight battery

tray-position = right
tray-padding = 0


;---------;
; MODULES ;
;---------;

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
format-padding = 0
label-unfocused-font = 5
label-focused-font = 5
; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 1
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 1

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${colors.background-alt}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = 1

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.background-alt}
label-urgent-padding = 1

[module/time]
type = internal/date

interval = 1.0

date =  %H:%M

[module/date]
type = internal/date
date =  %e %B - %A
label = %date%


[module/battery]
type = internal/battery

battery = BAT1

poll-interval = 1

full-at = 95

label-discharging = %percentage%%
label-charging = %percentage%%
label-full = %percentage%%

format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-charging =  <label-charging>

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

[module/volume]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-muted =  0%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/mpd]
type = internal/mpd

label-offline = mpd is offline
format-online = <icon-prev> <toggle> <icon-next> <label-song>
format-offline = <label-offline>
host = 127.0.0.1
port = 6600
icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

bar-progress-width = 10
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-empty = ─

[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight

format = <ramp> <label>

label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 

[module/wlan]
type = internal/network

interface = wlp2s0

interval = 5

label-connected =  %essid%
label-disconnected =  Not Connected

[module/cpu]
type = internal/cpu
label =  %percentage%%


[module/memory]
type = internal/memory
label =  %percentage_used%%

[module/network]
type = internal/network
interface = wlp2s0
label-connected =  %downspeed% |  %upspeed%



[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
;format-underline = #f50a4d
format-warn = <ramp> <label-warn>
;format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
;ramp-foreground = ${colors.foreground-alt}
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input




